import type { NextPage } from 'next'
import Link from "next/link";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios, { AxiosResponse, AxiosError } from "axios";

export async function getServerSideProps() {
  const res: AxiosResponse = await axios.get("https://api.sunabar.gmo-aozora.com/personal/v1/accounts/balances", {
      headers: { 
          'Accept': 'application/json;charset=UTF-8', 
          'Content-Type': 'application/json;charset=UTF-8', 
          'x-access-token': 'OGY0ZGM4YTJmNmQxMDBlNjNjZDhmNjk4'
      }
  });

  const data = await res.data;

  return { 
      props: {
          data: data 
      },
  };
}


const Home: NextPage = ({ data }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.zandakabig}>
          <h2 className={styles.h2zan}>あなたの残高は、{parseInt(data.balances[0].balance).toLocaleString()} 円です！</h2>
          <Link href={"/balance"}>
            <h3 className={styles.ca}>くわしく見る</h3>
          </Link>
        </div>

        <div className={styles.grid}>
          <Link href={"/transfer"}>
            <h2 className={styles.card}>お金振り込む</h2>
          </Link>

          <Link href={"/spaccounts-transfer"}>
            <h2 className={styles.card}>お金を振り替える</h2>
          </Link>
        </div>

        <div className={styles.zandakabig2}>
          <Link href={"/transaction"}>
            <h2>入出金の明細を確認する</h2>
          </Link>
        </div>

      </main>
    </div>
  )
}

export default Home